# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ef50be52a7a5e146175091002eab3c06eec73b69aa423dcc2224708049cd765238664edd49dba935182b55b4070d1d533f8e6ad81213b5246b14964bb00b97b

test:
  secret_key_base: a167f98571b231fbdf7c2a9fc4d3fe9dd0684dc6a32b610202ff98621effa1eac3ae2c741e506e83cd543c296e67fd32c30fa1be79e2498b437cc9c90704cdea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
